-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC import sys
-- MAGIC
-- MAGIC sys.path.append("/Workspace/Users/cinyoung.hur@databricks.com/job-cluster-monitoring/sdp_optimization")

-- COMMAND ----------

-- !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

USE CATALOG `hurcy`;
USE SCHEMA `default`;



-- COMMAND ----------

-- 1) task_run_stats_mv에 데이터가 있는지 확인
SELECT COUNT(*) AS row_count FROM task_run_stats_mv;

-- COMMAND ----------

-- 2) 시간 범위가 실제로 겹치는지 확인
SELECT
  iu.cluster_id,
  iu.instance_start_time,
  iu.instance_end_time,
  tr.period_start_time,
  tr.period_end_time,
  (iu.instance_start_time < tr.period_end_time
   AND tr.period_start_time < iu.instance_end_time) AS overlaps
FROM instance_utilization_mv iu
JOIN task_run_stats_mv tr
  ON iu.cluster_id = tr.cluster_id AND iu.workspace_id = tr.workspace_id
LIMIT 20;
